This is a demonstration of the use of small caps in \s-2UNIX\u\s-4TM\s+4\d\s+2 typesetting.

This is a demonstration of the use of small caps in \s-2UNIX\v'-0.22'\s-4\TM\s+4\v'+0.22'\s+2 typesetting.

This is a demonstration of the word UNIX in regular font.

This is a demonstration of a footnote in \s-2UNIX\s0\v'-0.05'\(dg\v'+0.05'
.FS
\v'-0.05'\(dg\v'+0.05' \s-2UNIX\s0 is a trademark of Bell Laboratories.
.FE
typesetting.
