.TH DOCTYPE 1
.SH NAME
doctype \- synthesize command line for processing troff documents
.SH SYNOPSIS
.B doctype
[ file ... ]
.SH DESCRIPTION
.B doctype
prints the command pipeline required to typeset the given input files with
.B troff
and its
associated preprocessors
(\fBrefer\fR,
.BR pic ,
.BR ideal ,
.BR tbl ,
.BR eqn ),
including the
.B -ms
macro option to troff if ms macro package commands are present in the input.
.PP
Only the preprocessors that are required to process the given input will
be added to the printed command line.  If no preprocessors are required, only
the troff command itself will be printed, along with the
.B -ms
option if needed.
.PP
The named files
are read and interpreted in order.
If no file is given or if file is '\-',
.B doctype
interprets the standard input.
.PP
.B doctype
only prints the synthesized command pipeline; it does not actually run it.
.SH "SEE ALSO"
\fBtroff\fR(1),
\fBrefer\fR(1),
\fBpic\fR(1),
\fBideal\fR(1),
\fBtbl\fR(1),
\fBeqn\fR(1),
\fBgroff_ms\fR(7)
.SH BUGS
.B doctype
does not recognize commands for macro packages other than ms.
