#!/usr/bin/awk -f

# Check for unbalanced start and end macro commands in an ms troff document
#
# Nesting of macro commands for a given type (successive invocations of a macro
# "start" command without an intervening corresponding macro "end" command) is
# considered to be an error.
#
# Extraneous macro "end" commands for a given type are considered an error.
#
# The presence of more than one .AB or .TL command in a document is considered
# an error.

BEGIN {
	ab = ae = 0
	ds = de = 0
	eq = en = 0
	fs = fe = 0
	kf = ks = ke = 0
	ts = te = 0
	tl = 0
}

/^.AB/ {
	ab++
	if (ab > 1) {
		print("Extraneous .AB command at line", NR)
	}
}

/^.AE/ {
	ae++
	if (ae > ab) {
		print("Extraneous .AE command at line", NR) 
		ae--
	}
}

/^.DS/ {
	ds++
	if (ds > 1) {
		print("Extraneous .DS command at line", NR)
	}
}

/^.DE/ {
	de++
	if (de > ds) {
		print("Extraneous .DE command at line", NR) 
	} else if (ds > 0) {
		ds--
	}
	de--
}

/^.EQ/ {
	eq++
	if (eq > 1) {
		print("Extraneous .EQ command at line", NR)
	}
}

/^.EN/ {
	en++
	if (en > eq) {
		print("Extraneous .EN command at line", NR) 
	} else if (eq > 0) {
		eq--
	}
	en--
}

/^.FS/ {
	fs++
	if (fs  > 1) {
		print("Extraneous .FS command at line", NR)
	}
}

/^.FE/ {
	fe++
	if (fe > fs) {
		print("Extraneous .FE command at line", NR) 
	} else if (fs > 0) {
		fs--
	}
	fe--
}

/^.KF/ {
	kf++
	if ((kf + ks) > 1) {
		print("Extraneous .KF command at line", NR)
	}
}

/^.KS/ {
	ks++
	if ((kf + ks) > 1) {
		print("Extraneous .KS command at line", NR)
	}
}

/^.KE/ {
	ke++
	if (ke > (kf + ks)) {
		print("Extraneous .KE command at line," NR)
	} else if (kf > 0) {
		kf--
	} else if (ks > 0) {
		ks--
	}
	ke--
}

/^.TS/ {
	ts++
	if (ts > 1) {
		print("Extraneous .TS command at line", NR)
	}
}

/^.TE/ {
	te++
	if (te > ts) {
		print("Extraneous .TE command at line", NR) 
	} else if (ts > 0) {
		ts--
	}
	te--
}

/^.TL/ {
	tl++
	if (tl > 1) {
		print("Extraneous .TL command at line", NR)
	}
}

END {
	if (ab > ae) {
		print(ab - ae, ".AB command(s) not terminated with .AE")
	}

	if (ds > de) {
		print(ds - de, ".DS command(s) not terminated with .DE")
	}

	if (eq > en) {
		print(eq - en, ".EQ command(s) not terminated with .EN")
	}

	if (fs > fe) {
		print(fs - fe, ".FS command(s) not terminated with .FE")
	}

	if ((kf + ks) > ke) {
		print(kf + ks - ke, ".KF or .KS command(s) not terminated with .KE")
	}

	if (ts > te) {
		print(ts - te, ".TS command(s) not terminated with .TE")
	}
}
