#!/usr/bin/awk -f

# awk requires, at a minimum, a pattern (with default action "print") or an
# action (executed for all input lines).
#
# This awk script implicitly prints the script's input for all lines that match
# an empty (universal match) regular expression in field 1.  This pattern will
# match all lines, including those that contain only a newline character.

$1 ~ //
