#!/usr/bin/awk -f

# awk requires, at a minimum, a pattern (with default action "print") or an
# action (executed for all input lines).
#
# This awk script implicitly prints the script's input for all lines with
# record numbers not equal to 0.  Since AWK numbers records sequentially
# beginning at 1, the pattern will match all lines.

NR != 0
